public enum GPGRoomUpdateStatus
{
	STATUS_OK = 0,
	STATUS_CLIENT_RECONNECT_REQUIRED = 2,
	STATUS_REAL_TIME_CONNECTION_FAILED = 7000,
	STATUS_MULTIPLAYER_DISABLED = 6003,
	STATUS_INTERNAL_ERROR = 1,
	STATUS_IOS_DOESNT_HAVE_THIS = 666
}
